In [1]:
import logging
from winterapi import WinterAPI

In [2]:
logging.getLogger("winterapi").setLevel("DEBUG")

In [3]:
winter = WinterAPI()

# Getting a summary of your queued ToOs

After you've submitted your ToOs, you might wonder how they are doing in the queue. You can find this out using the API.

In [4]:
program_name = "2024A000"

In [5]:
res, queue = winter.get_observatory_queue(program_name=program_name)

In [6]:
res.json()["msg"]

'Returning schedule summary for 2024A000'

In [7]:
queue

,prog_name,attempted_frac,too_schedule_name,target_names,n_entries,total_time_hours,window_start,window_end,archived
0,2024A000,0.0,request_2024A000_2026_01_16_14_27_33,[ZTF25acipkui],1,0.266667,2026-01-16 22:27:07.000,2026-01-23 22:27:07.000,False
1,2024A000,0.0,request_2024A000_2026_01_19_14_01_36,[ZTF25acfxvcu],1,0.266667,2026-01-19 22:01:11.000,2026-01-26 22:01:11.000,False
2,2024A000,1.0,request_2024A000_2026_01_20_08_55_05,[ZTF25aclckzl],2,0.533333,2026-01-20 16:54:07.413,2026-01-27 16:54:09.181,False
3,2024A000,1.0,request_2024A000_2026_01_20_09_37_54,[ZTF26aaaqczz],1,0.266667,2026-01-20 17:37:27.000,2026-01-27 17:37:27.000,False
4,2024A000,1.0,request_2024A000_2026_01_20_09_39_11,[ZTF26aabwols],1,0.266667,2026-01-20 17:38:46.000,2026-01-27 17:38:46.000,False
5,2024A000,0.0,request_2024A000_2026_01_21_09_36_29,[ZTF25acinfdh],1,0.266667,2026-01-24 17:35:59.000,2026-01-28 17:35:59.000,False
6,2024A000,0.0,request_2024A000_2026_01_21_09_37_38,[ZTF25acdheca],1,0.266667,2026-01-24 17:37:08.000,2026-01-28 17:37:08.000,False
7,2024A000,0.0,request_2024A000_2026_01_21_09_42_44,[ZTF25acfojmo],1,0.266667,2026-01-24 17:42:13.000,2026-01-28 17:42:13.000,False
8,2024A000,0.0,request_2024A000_2026_01_21_10_36_26,[ZTF25ackyfnb],1,0.266667,2026-01-24 18:35:57.000,2026-01-28 18:35:57.000,False
9,2024A000,0.0,request_2024A000_2026_01_21_10_37_12,[ZTF25achapja],1,0.266667,2026-01-24 18:36:44.000,2026-01-28 18:36:44.000,False
10,2024A000,0.0,request_2024A000_2026_01_21_10_37_47,[ZTF25acglosh],1,0.266667,2026-01-24 18:37:20.000,2026-01-28 18:37:20.000,False
11,2024A000,0.0,request_2024A000_2026_01_21_10_38_31,[ZTF21aasyjxq],1,0.266667,2026-01-24 18:38:04.000,2026-01-28 18:38:04.000,False
12,2024A000,0.0,request_2024A000_2026_01_21_10_39_03,[ZTF25abyevmr],1,0.266667,2026-01-24 18:38:35.000,2026-01-28 18:38:35.000,False
13,2024A000,0.0,request_2024A000_2026_01_21_10_42_30,[ZTF25abwjtwc],1,0.266667,2026-01-21 18:42:04.000,2026-01-28 18:42:04.000,False
14,2024A000,0.0,request_2024A000_2026_01_21_10_43_33,[ZTF25abjlnnh],1,0.266667,2026-01-21 18:43:07.000,2026-01-28 18:43:07.000,False
15,2024A000,0.0,request_2024A000_2026_01_21_10_47_45,[ZTF25acfxvcu],1,0.266667,2026-01-24 18:47:12.000,2026-01-28 18:47:12.000,False
16,2024A000,0.0,request_2024A000_2026_01_21_10_51_05,[ZTF25aclckzl],3,0.800000,2026-01-21 18:50:17.593,2026-01-28 18:50:18.123,False

You can also include archived (i.e. expired) schedules and/or specify a target name to narrow down the list

In [8]:
res, queue = winter.get_observatory_queue(
    program_name=program_name, include_archived=True, target_name="ZTF18acecugr"
)

In [9]:
res.json()["msg"]

'Returning schedule summary for 2024A000'

In [10]:
queue

,prog_name,attempted_frac,too_schedule_name,target_names,n_entries,total_time_hours,window_start,window_end,archived
1349,2024A000,1.0,request_2024A000_2025_10_30_18_55_52,[ZTF18acecugr],1,0.266667,2025-10-31 01:55:21.000,2025-11-07 02:55:21.000,True
1350,2024A000,1.0,request_2024A000_2025_10_31_11_33_34,[ZTF18acecugr],1,0.250000,2025-10-31 18:32:56.000,2025-11-07 19:32:56.000,True
1356,2024A000,0.5,request_2024A000_2025_11_03_15_15_32,[ZTF18acecugr],30,7.833333,2025-11-03 23:14:06.852,2025-12-03 23:14:06.852,True

# Checking an individual ToO

You can see when you submitted a ToO request, since the date is in the `too_schedule_name` name. Nonethless, let's imagine you have forgotten what request you submitted, and want to see what is in that schedule. We can use the schedule_details function to ask the API for this.

In [11]:
schedule_name = "request_2024A000_2026_01_21_10_51_05"

In [12]:
res, too_request = winter.get_too_details(
    too_schedule_name=schedule_name, program_name=program_name
)
res.json()["msg"]

'Returning details of schedule request_2024A000_2026_01_21_10_51_05'

In [13]:
# Here we see that it's the request we submitted earlier!
too_request

,targName,raDeg,decDeg,fieldID,filter,visitExpTime,singleExpTime,priority,progPI,progName,progID,validStart,validStop,observed,maxAirmass,ditherNumber,ditherStepSize,bestDetector,camera,obsHistID
0,ZTF25aclckzl,144.419513,20.037579,999999999,Y,960.0,120.0,50.0,MKasliwal,2024A000,3,61061.784926,61068.784926,0,2.0,8,90.0,1,winter,0
1,ZTF25aclckzl,144.419513,20.037579,999999999,J,960.0,120.0,50.0,MKasliwal,2024A000,3,61061.784926,61068.784926,0,2.0,8,90.0,1,winter,1
2,ZTF25aclckzl,144.419513,20.037579,999999999,Hs,960.0,64.0,50.0,MKasliwal,2024A000,3,61061.784932,61068.784932,0,2.0,15,90.0,1,winter,2

# Deleting Requests

Now let's imagine that you have made a horrible mistake! The dec of your target is actually 28 degrees, not 48.

You need to urgently need to delete this request! Fornuately, there is a function for this too.

In [14]:
res = winter.delete_too_request(
    too_schedule_name=schedule_name, program_name=program_name
)
res.json()["msg"]

'Deleted request_2024A000_2026_01_21_10_51_05'

Let's just double check to make see there is no request left. **You may need to wait up to 1 minute before changes take appear.**

In [15]:
res, queue = winter.get_observatory_queue(program_name=program_name)
print(res.json()["msg"])
queue

Returning schedule summary for 2024A000

,prog_name,attempted_frac,too_schedule_name,target_names,n_entries,total_time_hours,window_start,window_end,archived
0,2024A000,0.0,request_2024A000_2026_01_16_14_27_33,[ZTF25acipkui],1,0.266667,2026-01-16 22:27:07.000,2026-01-23 22:27:07.000,False
1,2024A000,0.0,request_2024A000_2026_01_19_14_01_36,[ZTF25acfxvcu],1,0.266667,2026-01-19 22:01:11.000,2026-01-26 22:01:11.000,False
2,2024A000,1.0,request_2024A000_2026_01_20_08_55_05,[ZTF25aclckzl],2,0.533333,2026-01-20 16:54:07.413,2026-01-27 16:54:09.181,False
3,2024A000,1.0,request_2024A000_2026_01_20_09_37_54,[ZTF26aaaqczz],1,0.266667,2026-01-20 17:37:27.000,2026-01-27 17:37:27.000,False
4,2024A000,1.0,request_2024A000_2026_01_20_09_39_11,[ZTF26aabwols],1,0.266667,2026-01-20 17:38:46.000,2026-01-27 17:38:46.000,False
5,2024A000,0.0,request_2024A000_2026_01_21_09_36_29,[ZTF25acinfdh],1,0.266667,2026-01-24 17:35:59.000,2026-01-28 17:35:59.000,False
6,2024A000,0.0,request_2024A000_2026_01_21_09_37_38,[ZTF25acdheca],1,0.266667,2026-01-24 17:37:08.000,2026-01-28 17:37:08.000,False
7,2024A000,0.0,request_2024A000_2026_01_21_09_42_44,[ZTF25acfojmo],1,0.266667,2026-01-24 17:42:13.000,2026-01-28 17:42:13.000,False
8,2024A000,0.0,request_2024A000_2026_01_21_10_36_26,[ZTF25ackyfnb],1,0.266667,2026-01-24 18:35:57.000,2026-01-28 18:35:57.000,False
9,2024A000,0.0,request_2024A000_2026_01_21_10_37_12,[ZTF25achapja],1,0.266667,2026-01-24 18:36:44.000,2026-01-28 18:36:44.000,False
10,2024A000,0.0,request_2024A000_2026_01_21_10_37_47,[ZTF25acglosh],1,0.266667,2026-01-24 18:37:20.000,2026-01-28 18:37:20.000,False
11,2024A000,0.0,request_2024A000_2026_01_21_10_38_31,[ZTF21aasyjxq],1,0.266667,2026-01-24 18:38:04.000,2026-01-28 18:38:04.000,False
12,2024A000,0.0,request_2024A000_2026_01_21_10_39_03,[ZTF25abyevmr],1,0.266667,2026-01-24 18:38:35.000,2026-01-28 18:38:35.000,False
13,2024A000,0.0,request_2024A000_2026_01_21_10_42_30,[ZTF25abwjtwc],1,0.266667,2026-01-21 18:42:04.000,2026-01-28 18:42:04.000,False
14,2024A000,0.0,request_2024A000_2026_01_21_10_43_33,[ZTF25abjlnnh],1,0.266667,2026-01-21 18:43:07.000,2026-01-28 18:43:07.000,False
15,2024A000,0.0,request_2024A000_2026_01_21_10_47_45,[ZTF25acfxvcu],1,0.266667,2026-01-24 18:47:12.000,2026-01-28 18:47:12.000,False
16,2024A000,0.0,request_2024A000_2026_01_21_10_51_05,[ZTF25aclckzl],3,0.800000,2026-01-21 18:50:17.593,2026-01-28 18:50:18.123,False

Fortunately the request has been removed, and the queue is empty!